server:
  port: 8083
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: a525456580
  redis:
    #host: 127.0.0.1
    host: 192.168.56.101
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
#  Spring整合caffeine的方式进行配置，当前使用的是不集成直接写config的方式
#  cache:
#    type: caffeine
#    cache-names:
#      - caffeineShop
#      - caffeineBlog
#    caffeine:
#      spec: maximumSize= 500
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  mapper-locations: classpath*:com/hmdp/mapper/xml/*.xml

logging:
  level:
    com.hmdp: debug


rocketmq:
  name-server: 192.168.56.101:9876
  producer:
    group: orderProducerGroup

mq:
  order:
    consumer:
      group:
        name: order_orderTopic_cancel_group
    topic: orderTopic
    tag:
      cancel: order_cancel

swagger:
  enable: true
  server:
    port: 8083